#Name: Anup Kar
#UID: 204-419-149
#EMAIL: akar@g.ucla.edu

build: 3b.py
	rm -rf lab3b ;ln -s lab3b.py 3b.py lab3b ;chmod +x 3b.py; echo "created Symlink succesfully\n"

dist: 
	tar -zcvf lab3b-204419149.tar.gz lab3b.py README Makefile

clean:
	rm -rf *.tar.gz lab3b *~

