#NAME: Anup Kar
#EMAIL: akar@g.ucla.edu
#ID: 204419149
dist:
	tar -czf lab4a-204419149.tar.gz my_beaglebone.png connected.png copy.png build_run.png git.png README Makefile
clean:
	rm my_beaglebone.png connected.png copy.png build_run.png git.png README Makefile

